package juanrodriguesdev.apisinan.model;

public enum Escolaridade {
    ANALFABETO,
    FUNDAMENTAL_1_INCOMPLETO,
    FUNDAMENTAL_1_COMPLETO,
    FUNDAMENTAL_2_INCOMPLETO,
    FUNDAMENTAL_2_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    IGNORADO,
    NAO_SE_APLICA
}
